Repository zayKenyon/VALORANT-rank-yoinker, pull requests merged in 2022-08, with the labels that each got.

#101 feat(config-menu): added menu and better defaults
  main.py
  src/configurator.py
  src/constants.py
  src/questions.py
Labels: enhancement

#98 updated streamer mode stuff, team colors
  src/components/PlayerComponent.vue
Labels: enhancement

#107 chore(splash): update username
  docs/app.js
  docs/index.html
  docs/sitemap.xml
Labels: documentation

#118 Switch prettytable to rich table to support better styles
  main.py
  requirements.txt
  src/player_stats.py
  src/table.py
Labels: refactor, semver:minor

#119 rpc button added
  src/requestsV.py
  src/rpc.py
Labels: feature request, semver:patch
